definitions:
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.ListPosts:
    properties:
      count:
        type: integer
      post:
        items:
          $ref: '#/definitions/models.Post'
        type: array
    type: object
  models.Post:
    properties:
      body:
        type: string
      id:
        type: integer
      title:
        type: string
      user_id:
        type: integer
    type: object
  models.StandardErrorModel:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
  models.SuccessfullResponse:
    properties:
      message:
        type: string
    type: object
  models.UpdatePost:
    properties:
      body:
        type: string
      title:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/get-from-open-api/:
    get:
      consumes:
      - application/json
      description: This API for getting list of posts from open apu
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessfullResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetPostsFromApi
      tags:
      - open_api_posts
  /v1/posts/create-post/:
    post:
      consumes:
      - application/json
      description: This API for creating a new post
      parameters:
      - description: create_post_request
        in: body
        name: create_post_request
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: CreatePost
      tags:
      - post
  /v1/posts/delete-post/{id}/:
    delete:
      consumes:
      - application/json
      description: This API for deleting post
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessfullResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: DeletePost
      tags:
      - post
  /v1/posts/get-post/{id}/:
    get:
      consumes:
      - application/json
      description: This API for getting post by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetPostById
      tags:
      - post
  /v1/posts/list-posts/:
    get:
      consumes:
      - application/json
      description: This API for getting list of posts
      parameters:
      - description: Page
        in: query
        name: page
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListPosts'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: ListPosts
      tags:
      - post
  /v1/posts/update-post/{id}/:
    put:
      consumes:
      - application/json
      description: This API for updating post
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: update_post
        in: body
        name: update_post
        required: true
        schema:
          $ref: '#/definitions/models.UpdatePost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: UpdatePost
      tags:
      - post
swagger: "2.0"
